---
title: "Possible resources"
author: "Susan Sayre"
date: "9/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# List of Resources to Investigate

## Reading articles, lit reviews

* One example link on a blog that includes a number of valuable resources for reading and writing about journal articles <http://www.raulpacheco.org/2015/08/online-resources-to-help-students-summarize-journal-articles-and-write-critical-reviews/> 

## Using git

1. Create a GitHub account [here](https://github.com/)
2. Download and install Git for your operating system [here](https://git-scm.com/downloads)
3. Start using Git with the command line using [this tutorial](https://docs.gitlab.com/ee/gitlab-basics/start-using-git.html) which walks you through:
  + Connecting your desktop Git to your GitHub account.
  + How to clone repositories to your desktop.
  + How to add and commit changes.
4. Clone the carbonTaxIncidence and sayreLab repositories to your computer. Professor Stratton-Sayre's GitHub account (and the https links to clone the repositories) can be found [here](https://github.com/susansayre).

Some sources for learning more about git and github are: 

* Grant McDermott's git lecture slides from his data science course. The best way to get these is to clone the repository available at https://github.com/uo-ec607/lectures.
* GitHub guides, such as their [Hello World Guide](https://guides.github.com/activities/hello-world/) and their [Git Handbook](https://guides.github.com/introduction/git-handbook/) guide. 
* The DataCamp [Introduction to Git for Data Science](https://www.datacamp.com/courses/introduction-to-git-for-data-science) Course, which is very-in depth in terms of using git, but does not cover using GitHub. 

## Using R

## General coding tips

Coding_For_Econs_20190221.pdf


